[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib", "../node_modules"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 1_000
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false
fuzz = { runs = 512 }
invariant = { runs = 128, depth = 32, fail_on_revert = false }

[rpc_endpoints]
robinhood_testnet = "${RH_TESTNET_RPC_URL}"
robinhood_mainnet = "${RH_MAINNET_RPC_URL}"

[etherscan]
robinhood_testnet = { key = "${BLOCKSCOUT_API_KEY}", url = "https://explorer.testnet.chain.robinhood.com/api/" }
robinhood_mainnet = { key = "${BLOCKSCOUT_API_KEY}", url = "https://robinhoodchain.blockscout.com/api/" }
